FUNCTION "FC_09_HMI" : Void
{ S7_Optimized_Access := 'TRUE' }
VERSION : 0.1

BEGIN
	//************************************************************
	//===Author: Mateusz Połojko
	//-----Linkedin: https://pl.linkedin.com/in/mateusz-po%C5%82ojko-52a3541b1
	//-----Github: https://github.com/Bhazel95
	//===Description:
	//-----HMI assigments
	//===Customer:
	//-----Apator Powogaz S.A.
	//************************************************************
	
	REGION Camera state  
	    "DEV".Convoyer_7.Modular_7A.HMI.Camera.State := "ModularConvoyer_7A_DB".CameraConnectionTCP_Instance.State.name;
	    "DEV".Convoyer_7.Modular_7B.HMI.Camera.State := "ModularConvoyer_7B_DB".CameraConnectionTCP_Instance.State.name;
	END_REGION
	
END_FUNCTION

